In [1]:
import torch


In [3]:
# create 2 tensors
u = torch.tensor ([[1,0],[2,0]])
v = torch.tensor([[3,0],[4,0]])

print(u)
print(v)

tensor([[1, 0],
        [2, 0]])
tensor([[3, 0],
        [4, 0]])


In [4]:
#perform some additions and substractions
print(u + v)
print(u - v)

tensor([[4, 0],
        [6, 0]])
tensor([[-2,  0],
        [-2,  0]])


In [7]:
#try some common tensor functions
a = torch.rand (2,4)* 2 - 1
print('Common functions:')
print(torch.abs)
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5 ) )

Common functions:
<built-in method abs of type object at 0x00007FFE77016560>
tensor([[-0., 1., -0., -0.],
        [1., 1., -0., 1.]])
tensor([[-1.,  0., -1., -1.],
        [ 0.,  0., -1.,  0.]])
tensor([[-0.5000,  0.5000, -0.3922, -0.1144],
        [ 0.5000,  0.5000, -0.4153,  0.5000]])


In [8]:
#Reduction function using mean

x = torch.tensor([1,2,3,4,5],dtype=torch.float32)
print(x)
print(x.mean)

tensor([1., 2., 3., 4., 5.])
<built-in method mean of Tensor object at 0x0000022EA51E56D0>


In [9]:
#More reduction function using min and max
print(x.max())
print(x.min())

tensor(5.)
tensor(1.)


In [11]:
#trigonometric functions and their inverse
import numpy as np
x = torch.tensor([0,np.pi/2,np.pi])
print(x)
print(torch.sin(x))
print(torch.cos(x))

tensor([0.0000, 1.5708, 3.1416])
tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])
tensor([ 1.0000e+00, -4.3711e-08, -1.0000e+00])


In [14]:
#get an evenly spaced list of numbers between a range
pi = torch.linspace (-np.pi/2 , np.pi/2 , steps = 1000)
print(pi[:5])
print(pi[-5:])

sined = torch.sin(pi)
cosed = torch.cos(pi)
print(sined[0:5])
print(cosed[0:5])

tensor([-1.5708, -1.5677, -1.5645, -1.5614, -1.5582])
tensor([1.5582, 1.5614, 1.5645, 1.5677, 1.5708])
tensor([-1.0000, -1.0000, -1.0000, -1.0000, -0.9999])
tensor([-4.3711e-08,  3.1447e-03,  6.2894e-03,  9.4340e-03,  1.2579e-02])


In [1]:
#use matplotlib to visualize
import matplotlib.pyplot as plt
plt.plot(sined, label = "sined")
plt.plot(cosed, label = "cosed")
plt.legend()
plt.show()

NameError: name 'sined' is not defined