In [2]:
#import library
import torch



In [7]:
#create tensors

t0 = torch.tensor (1000)
t1 = torch.tensor ([1,2,3,4])
t2 = torch.tensor ([[1,2,3],[ 7,5,3]])

print(t0)
print(t1)
print(t2)

tensor(1000)
tensor([1, 2, 3, 4])
tensor([[1, 2, 3],
        [7, 5, 3]])


In [8]:
#set datatype for tensors
a = torch.ones ((2,3),dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
