In [2]:
import torch
import numpy as np
numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy (numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [3]:
#reverse_example
pytorch_rand = torch.rand (2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.4028, 0.7336, 0.9196],
        [0.5272, 0.2201, 0.9750]])
[[0.40279472 0.733635   0.9195638 ]
 [0.5271536  0.22013628 0.9750322 ]]
