In [9]:
import torch
from torch.autograd import Variable


In [10]:
x = Variable (torch.ones(2,2), requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
y = x + 2 
print (y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
print(y.grad_fn)

In [13]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [14]:
out.backward()


In [15]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [1]:
#frozen parameters

from torch import nn, optim
import torchvision


In [4]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [7]:
model = torchvision.models.resnet18(pretrained = True)

C:\Users\Korisnik\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\Korisnik\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [ ]:
#Freeze all the parameters in the network
for param in model.parameters()
param.requires_grad = False


In [9]:
model.fc = nn.Linear(512,10)

In [17]:
#Optimize only the CLassifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum = 0.9 )

In [18]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)
